# Generated by Django 3.2 on 2024-01-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_product_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pic",
            field=models.ImageField(upload_to="product_pic/"),
        ),
    ]
