# Generated by Django 3.2 on 2024-01-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_product_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="address",
            field=models.TextField(),
        ),
    ]
