# Generated by Django 3.2 on 2024-02-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
            ),
        ),
    ]
