# Generated by Django 3.2 on 2024-02-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20240203_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
