# Generated by Django 3.2 on 2024-02-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_wishlist_wished_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='users',
        ),
    ]
