# Generated by Django 3.2 on 2024-02-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_wishlist_wished_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="phone_number",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
