# Generated by Django 3.2 on 2024-03-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_remove_product_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
    ]
